ZabWedding/Controllers/BilledersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SixLabors.ImageSharp.Formats.Jpeg;
using ZabWedding.DataAccessLayer;
using ZabWedding.Models;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.Formats;
using System.Drawing;


namespace ZabWedding.Controllers
{
    public class BilledersController : Controller
    {
        private readonly DatabaseContext _context;

        public BilledersController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Billeders
        /*
        public async Task<IActionResult> Index()
        {

            return View(await _context.Billeder.ToListAsync());
        }
        */

        public async Task<IActionResult> Index(bool myselfies, bool fotograf, bool resten)
        {


            if (fotograf == true && myselfies == true && resten == true)
            {
                return View(await _context.Billeder
                .Where(x => x.Fotograf == true || x.MySelfie == true || x.Fotograf == false && x.MySelfie == false) 
                .ToListAsync());
            }
            if (fotograf == true && myselfies == true && resten == false)
            {
                return View(await _context.Billeder
                .Where(x => x.Fotograf == true || x.MySelfie == true)
                .ToListAsync());
            }

            if (fotograf == false && myselfies == true && resten == true)
            {
                return View(await _context.Billeder
                .Where(x => x.Fotograf == false && x.MySelfie == true || x.Fotograf == false && x.MySelfie == false)
                .ToListAsync());
            }
            if (fotograf == false && myselfies == true && resten == false)
            {
                return View(await _context.Billeder
                .Where(x => x.Fotograf == false && x.MySelfie == true)
                .ToListAsync());
            }

            if (fotograf == true && myselfies == false && resten == true)
            {
                return View(await _context.Billeder
                .Where(x => x.Fotograf == true && x.MySelfie == false || x.Fotograf == false && x.MySelfie == false)
                .ToListAsync());
            }
            if (fotograf == true && myselfies == false && resten == false)
            {
                return View(await _context.Billeder
                .Where(x => x.Fotograf == true && x.MySelfie == false)
                .ToListAsync());
            }




            return View(await _context.Billeder.ToListAsync());

        }

        // GET: Billeders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billeder = await _context.Billeder
                .FirstOrDefaultAsync(m => m.ID == id);
            if (billeder == null)
            {
                return NotFound();
            }

            return View(billeder);
        }

        // GET: Billeders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Billeders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Billeder weddingPictureInfo, List<IFormFile> files)
        {

            if (ModelState.IsValid)
            {
                foreach (var file in files)
                {
                    if (file.Length > 0)
                    {
                        using (var ms = new MemoryStream())
                        {
                            file.CopyTo(ms);
                            var fileBytes = ms.ToArray();
                            weddingPictureInfo.Billede = Convert.ToBase64String(fileBytes);
                            // act on the Base64 data
                        }
                    }
                }

                _context.Add(weddingPictureInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(weddingPictureInfo);
        }

        // GET: Billeders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billeder = await _context.Billeder.FindAsync(id);
            if (billeder == null)
            {
                return NotFound();
            }
            return View(billeder);
        }

        // POST: Billeders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Billede,Fotograf,MySelfie")] Billeder billeder)
        {
            if (id != billeder.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(billeder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BillederExists(billeder.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(billeder);
        }

        // GET: Billeders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billeder = await _context.Billeder
                .FirstOrDefaultAsync(m => m.ID == id);
            if (billeder == null)
            {
                return NotFound();
            }

            return View(billeder);
        }

        // POST: Billeders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var billeder = await _context.Billeder.FindAsync(id);
            _context.Billeder.Remove(billeder);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BillederExists(int id)
        {
            return _context.Billeder.Any(e => e.ID == id);
        }
    }
}

ZabWedding/Controllers/TilmeldingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ZabWedding.DataAccessLayer;
using ZabWedding.Models;

namespace ZabWedding.Controllers
{
    public class TilmeldingsController : Controller
    {
        private readonly DatabaseContext _context;

        public TilmeldingsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Tilmeldings
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tilmeldinger.ToListAsync());
        }

        // GET: Tilmeldings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tilmelding = await _context.Tilmeldinger
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tilmelding == null)
            {
                return NotFound();
            }

            return View(tilmelding);
        }

        // GET: Tilmeldings/Create
        public async Task<IActionResult> Create()
        {
            List<Tilmelding> test = await _context.Tilmeldinger.ToListAsync();
            ViewBag.peopleAmount = test.Count; 
            return View();
        }

        // POST: Tilmeldings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Fornavn,Efternavn,Allegi")] Tilmelding tilmelding)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tilmelding);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create));
            }
            return View(tilmelding);
        }

        // GET: Tilmeldings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tilmelding = await _context.Tilmeldinger.FindAsync(id);
            if (tilmelding == null)
            {
                return NotFound();
            }
            return View(tilmelding);
        }

        // POST: Tilmeldings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Fornavn,Efternavn,Allegi")] Tilmelding tilmelding)
        {
            if (id != tilmelding.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tilmelding);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TilmeldingExists(tilmelding.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tilmelding);
        }

        // GET: Tilmeldings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tilmelding = await _context.Tilmeldinger
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tilmelding == null)
            {
                return NotFound();
            }

            return View(tilmelding);
        }

        // POST: Tilmeldings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tilmelding = await _context.Tilmeldinger.FindAsync(id);
            _context.Tilmeldinger.Remove(tilmelding);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TilmeldingExists(int id)
        {
            return _context.Tilmeldinger.Any(e => e.ID == id);
        }
    }
}

ZabWedding/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bryllup</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="sticky-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 navbar-fixed-top">
            <div class="container-fluid" >
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Theis&Zabrina</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar navbar-fixed-top navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Bryllup
                            </a>
                            <div class="dropdown-menu text-dark" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="WeddingInfo">Bryllup</a>
                                <a class="dropdown-item" href="/Home/WeddingInfo#tidsplanen">Tidsplanen.</a>
                                <a class="dropdown-item" href="/Home/WeddingInfo#dagen">Dagen</a>
                                <a class="dropdown-item" href="/Home/WeddingInfo#ønskelisten">ønskelisten</a>
                                <a class="dropdown-item" href="/Home/WeddingInfo#overnatning">overnatning</a>
                                <a class="dropdown-item" href="/Home/WeddingInfo#transport">Transport</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tilmeldings" asp-action="Create">Tilmelding</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Galleri
                            </a>
                            <div class="dropdown-menu text-dark" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Billeders" asp-action="Index">Se Billeder</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Billeders" asp-action="Create">Tilføj Billeder</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Brude Paret
                            </a>
                            <div class="dropdown-menu text-dark" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Tilmeldings" asp-action="Index">Se Tilmelding</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Admin</a>
                        </li>
                        <!--
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Maskinregistrering
        </a>
        <div class="dropdown-menu text-dark" aria-labelledby="navbarDropdown">
            <div class="dropdown-divider">MaskinTimer</div>
            <a class="dropdown-item" asp-area="" asp-controller="OwnMachineHours" asp-action="Index">Egen Maskintimer</a>
            <a class="dropdown-item" asp-area="" asp-controller="RentedMachineHours" asp-action="Index">Lejede Maskintimer</a>
            <div class="dropdown-divider">MaskinDage</div>
            <a class="dropdown-item" asp-area="" asp-controller="OwnMachineDays" asp-action="Index">Egen MaskinDage</a>
            <a class="dropdown-item" asp-area="" asp-controller="RentedMachineDays" asp-action="Index">Lejede MaskinDage</a>
        </div>
    </li>
    -->

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer ">
        <div class="container-fluid bg-success text-black">
            <b>&copy; 2021 - Theis og Zabrinas bryllups hjemmeside bragt til jer af Jacob</b>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
    </html>